name: "Autodarts"
slug: "autodarts"
description: "Autodarts add-on wrapper"
version: "0.1.4"
url: "https://github.com/NirGreenSpring/autodarts-docker-HA/Autodarts"


arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386

startup: services
boot: auto
init: false

ports:
  3180/tcp: 3180
  
devices:
  - /dev/video0
  - /dev/video2
  - /dev/video4

map:
  - addon_config:rw

map:
  - addon_config:rw

full_access: true

options: {}
schema: {}