name: "Autodarts"
slug: "autodarts"
description: "Autodarts add-on wrapper"
version: "0.1.1"
url: "https://github.com/NirGreenSpring/autodarts-docker-HA/Autodarts"


arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386

startup: services
boot: auto
init: false

ports:
  3180/tcp: 3180

map:
  - addon_config:rw

full_access: true

options:
  video_devices:
    - /dev/video0
schema:
  video_devices:
    - str